---

openshift_cluster_content:
- object: projectrequest
  content:
  - name: "Projects"
    file: "{{ inventory_dir }}/../projects/projects-dev.yml"
    action: create
- object: policy
  content:
  - name: "Apply policy directory"
    file: "{{ inventory_dir }}/../policy/"
    namespace: field-guides-dev
- object: deployments
  content:
  - name: "jenkins"
    namespace: "field-guides-dev"
    template: "openshift//jenkins-ephemeral"
    params: "{{ inventory_dir }}/../deploy/dev/jenkins-params"
  - name: "dev-deployment"
    template: "{{ inventory_dir }}/../deploy/template.yml"
    params: "{{ inventory_dir }}/../deploy/dev/params"
- object: builds
  content:
  - name: "image build"
    namespace: "field-guides-dev"
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.10/jenkins-slaves/.openshift/templates/jenkins-slave-image-mgmt-template.yml"
    params: "{{ inventory_dir }}/../deploy/dev/slave-params"
  - name: "site build"
    template: "{{ inventory_dir }}/../build/template.yml"
    params: "{{ inventory_dir }}/../build/dev/params"
    params_from_vars:
      SOURCE_REPOSITORY_URL: "{{ git_url | default(omit) }}"
      SOURCE_REPOSITORY_REF: "{{ git_ref | default(omit) }}"
